apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: repronet-phs-rus
spec:
  template:
    spec:
      containers:
        - name: repronet-phs-rus
          image: dev.local/repronet-phs-rus
          imagePullPolicy: Never
          ports:
            - containerPort: 5000