apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: repronet-phs-kor
spec:
  template:
    spec:
      containers:
        - name: repronet-phs-kor
          image: dev.local/repronet-phs-kor:v1.1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 5000