apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cyzil-trf-jpn
spec:
  template:
    spec:
      containers:
        - name: cyzil-trf-jpn
          image: boxkey/transformer:v1.0.2
          ports:
            - containerPort: 5000
          env:
            - name: MLFLOW_MODEL_NAME
              value: "Transformer_Jpn"
            - name: MLFLOW_MODEL_VERSION
              value: "1"
      imagePullSecrets:
        - name: myhubcred
