apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: repronet-trf-ara
spec:
  template:
    spec:
      containers:
        - name: repronet-trf-ara
          image: dev.local/repronet-trf-ara:v1.1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 5000