apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: repronet-trf-kor
spec:
  template:
    spec:
      containers:
        - name: repronet-trf-kor
          image: dev.local/repronet-trf-kor
          imagePullPolicy: Never
          ports:
            - containerPort: 5000