model_name: net-transofrmer
model_params: {dropout: 0.2, hid_dim: 256, input_dim: 246, max_seq_len: 64, n_heads: 4,
  n_layers: 8, output_dim: 246, pf_dim: 64, src_pad_idx: 0, trg_pad_idx: 0}
train_params: {batch_size: 256, checkpoint: 1, clip: 1.0, device_type: cuda, epochs: 10,
  loss: CrossEntropyLoss, lr: 0.005, optim: Adam, train_path: /content/drive/MyDrive/Colab_Notebooks/NETransliterate/datasets/wd_katakana_64.f12,
  val_path: /content/drive/MyDrive/Colab_Notebooks/NETransliterate/datasets/wd_katakana_16.f12}
